// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiukbugxlugdkksnxrsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpdWtidWd4bHVnZGtrc254cnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTcxMTMsImV4cCI6MjA3NDUzMzExM30.IpbOtmByrzp_LGxVpiuIyr_oD6vms2q3PD-nl9OQ0AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});